/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */



	/****************************************************************************/
	/* Condicionales */
	/*
	 * Cuando se tienen varias condiciones (más de 2) se utiliza else if
	 *
	 * CICLOS
	 *
	 * for(inicio; finalización; incremento)
	 * {
	 * 		sentencia
	 * 	}
	 * for(uint32_t i=0; i < n; i++)
	 * {
	 * 		sentencia
	 * 	}
	 *
	 *
	 * FUNCIONES
	 * 	SINTAXIS:
	 * 	***
	 * 	int main(void){
	 * 		sentencias
	 * 	}
	 *
	 * 	En el caso de main:
	 *
	 * 	int  -> va a devolver un entero
	 * 	main -> nombre de la función
	 * 	void -> lo que recibe
	 *
	 * ***
	 * void initSensor(void)
	 * {
	 * 	Sentencias
	 * }	-> Esta sólo sirve para ejecutar las sentencias.
	 * 		   suele utilizarse para inicializar sensores.
	 * 		   prender LEDs.
	 *
	 * ***
	 * void GPIO_PinConfig(Handler *pinhandler)
	 * {
	 * 		Sentencias: Recibe puntero a una estructura, carga esos registros al periférico
	 * 	}
	 *
	 * 	uint32_t GPIO_ReadPin (Handler *pinhandler)
	 * 	{
	 *
	 * 	}
	 * En C una función no puede devolver más de un parámetro, pero sí la dirección por medio
	 * de un puntero.
	 *
	 *
	 * FPU: Unidad de punto flotante, permite utilizar números decimales :)
	 *
	 */

#include <stdint.h>
#include <stdbool.h>
#include <math.h>

#define NOP() __asm("NOP")

//void myFunction(void);	// Para utilizarla debemos ponerle en encabezado, aunque no es una buena práctica.


int main(void)
{
//	myFunction();

	uint8_t estatura = 160;
	bool puedeEntrar;
	(void)puedeEntrar;

	if (estatura < 150){
		puedeEntrar = false;
	}
	else{
		puedeEntrar = true;
	}

	uint32_t dineroEnLaCuenta = 300000;
	bool tieneCarro = false;
	bool leAceptoLaSalida;
	(void)leAceptoLaSalida;

	if(dineroEnLaCuenta > 150000  && dineroEnLaCuenta < 500000)
	{
		if(tieneCarro)
		{
			leAceptoLaSalida = true;
		}
		else
		{
			leAceptoLaSalida = false;
		}
	}
	else if(dineroEnLaCuenta < 15000 )
	{
		leAceptoLaSalida = false;
	}
	else if (dineroEnLaCuenta > 500000)
	{
		leAceptoLaSalida = true;
	}

	// Para 1 segundo 1200000

	for(uint32_t i = 0; i < 10 ; i++)
	{
		// Queremos ver la tabla del 7
		uint32_t tablaDe7 = 7 * i;
		(void) tablaDe7;
	}


	for(uint16_t horas = 0; horas < 24; horas++)
	{
		for(uint16_t minutos = 0; minutos < 60; minutos++)
		{
			for(uint16_t segundos = 0; segundos < 60; segundos++)
			{
				for(uint16_t contador = 0; contador < 1200000; contador++)
				{
					NOP();
				}
			}
		}
	}



    /* Loop forever */
	while(true){

	}
}


uint8_t Conversor(uint8_t variable)
{
	uint8_t dec;
	for(uint8_t i=0; i <= 8*sizeof(variable); i++)
	{
		uint8_t varAux = variable & (1<<i);			// Máscara
		varAux = varAux >> i;				// Llevarlo a la posición cero
		dec = dec + (varAux * pow(2,i));	// Se multiplica por el peso
	}
	return dec;
}


//void myFunction(void)
//{
//	char a = 5;
//
//}
