/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>

unsigned char variable1;
//	Esto último es util cuando no recordamos cómo se llama el tipo de variable
//	que necesitamos, pero sí sabemos el tamaño que deben tener.

uint8_t variable2;			// corresponde a un char
uint32_t variable3;			// corresponde a un int
uint16_t variable4;			// corresponde a un short

//	Podemos poner varias variables del mismo tipo en el mismo renglón.
uint8_t x,y,x;
int16_t m=2,n=3,l=-5;

//	Para agregar una cadena: Dentro de corchetes va el tamaño de letras
char miPrimerString[12] = "Hola mundo.";

char miPrimerCaracter = 'V'; // Cada caracter es un valor numérico del código aski

//	Otra forma de declarar variables en un mismo renglón pero de diferente tipo es
//	separándolas con ;
uint8_t variable5; int32_t variable6;

int main(void)
{
	/* Para saber cual es el tamaño de cierto tipo de variable:*/
	char sizeChar = sizeof(char);
	char sizeChar2 = sizeof(variable6);
	char sizeMiPrimerString = sizeof(miPrimerString);
	(void)sizeChar; (void)sizeChar2; (void)sizeMiPrimerString;

	/* OPERADORES */

	// Se puede simplificar
	m = m + n;
	m+=n;

	m = m + 1;
	m += 1;
	m ++;

	m*=n;
	m/=n;

	m%=n;

	m<<=n;

	m>>=n;



    /* Loop forever */
	while(1)
	{

	}
}
